[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "VIV_ML"
version = "0.1.0"
authors = [
  { name="Omar Ghariani", email="omar.ghariani@uni-weimar.de" },
]
description = """Prediction of the VIV response of canonical cylinder and Rio-Niteroi bridge via Deep Learning
techniques"""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.0",
    "pandas",
    "pyarrow",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "torch",
]

[tool.setuptools.packages.find]
where = ["src"]